using Cosmere.System.Scadrial.Util;
using Verse;

namespace Cosmere.System.Scadrial.Gene;

/// <summary>
///     Holds a kandra to its spikes.
/// </summary>
/// <remarks>
///     Nothing about a kandra is inherited. The mind is two pieces of metal, and if they come out
///     the mind goes with them. This watches for that and drops the pawn back to a mistwraith.
///     <para>
///         The check is deliberately slow. A kandra loses its Blessing through surgery or a
///         hemalurgist taking it, both of which are events, not something that can happen between
///         two ticks and matter.
///     </para>
/// </remarks>
public class BlessingBound : Verse.Gene {
    public override void PostAdd() {
        base.PostAdd();

        // A kandra generated by the game arrives with the xenotype and no spikes in it. Give it
        // the middle Blessing rather than letting the first rare tick unmake it.
        if (KandraUtility.HasBlessing(pawn)) return;
        if (KandraUtility.Blessings.Count == 0) return;

        KandraUtility.GiveBlessing(pawn, HediffDefOf.Cosmere_Scadrial_Hediff_BlessingOfPresence);
    }

    public override void TickInterval(int delta) {
        base.TickInterval(delta);

        if (!pawn.IsHashIntervalTick(GenTicks.TickLongInterval, delta)) return;
        if (pawn.health?.hediffSet?.HasHediff(
                HediffDefOf.Cosmere_Scadrial_Hediff_Mistwraith
            ) == true) {
            return;
        }

        // Two ways to stop being a kandra: lose the Blessing, or have somebody pull a spike out
        // of the pair that holds it. The second one is how a hemalurgist does it.
        bool intact = KandraUtility.HasBlessing(pawn)
                      && KandraUtility.SpikeCount(pawn) >= KandraUtility.SpikesPerBlessing;
        if (intact) return;

        KandraUtility.RevertToMistwraith(pawn);
    }
}
