namespace Cosmere.Lightweave.Tokens;

public enum ThemeSlot {
    SurfacePrimary,
    SurfaceRaised,
    SurfaceSunken,
    SurfaceAccent,
    SurfaceShadow,
    TextPrimary,
    TextSecondary,
    TextMuted,
    TextOnAccent,
    TextOnDanger,
    BorderDefault,
    BorderSubtle,
    StatusWarning,
    StatusDanger,
    StatusSuccess,
    BorderFocus,
    BorderHover,
    SurfaceInput,
    SurfaceDisabled,
    BorderOff,
    BorderDanger,
    InteractionHover,
    InteractionPress,
}