<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Authors>CryptikLemur, Luucid</Authors>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>latest</LangVersion>
        <OutDir>..\Assemblies\</OutDir>
        <Nullable>enable</Nullable>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
        <WarningLevel>4</WarningLevel>
        <ErrorReport>prompt</ErrorReport>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>

        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <PlatformTarget Condition=" '$(Platform)' == '' ">AnyCPU</PlatformTarget>

        <RimWorldDir Condition="'$(RimWorldDir)' == ''">$([System.Environment]::GetEnvironmentVariable('RIMWORLD_DIR'))</RimWorldDir>
        <WorkshopDir Condition="'$(WorkshopDir)' == ''">$([System.Environment]::GetEnvironmentVariable('WORKSHOP_DIR'))</WorkshopDir>
        <RimWorldDir Condition="'$(RimWorldDir)' == ''">..\..\..\</RimWorldDir>
        <WorkshopDir Condition="'$(WorkshopDir)' == ''">..\..\..\..\..\workshop\content\294100</WorkshopDir>

        <RimWorldManagedPath>$(RimWorldDir)\RimWorldWin64_Data\Managed</RimWorldManagedPath>
        <FileAlignment>512</FileAlignment>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>embedded</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <PackageId>Cosmere.Roshar</PackageId>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugSymbols>false</DebugSymbols>
        <DebugType>none</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <ItemDefinitionGroup>
        <Reference>
            <Private>False</Private>
        </Reference>
        <ProjectReference>
            <Private>False</Private>
        </ProjectReference>
        <PackageReference>
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
    </ItemDefinitionGroup>

    <ItemGroup>
        <Using Include="System.Linq"/>
        <Using Include="System.Collections.Generic"/>
        <Using Include="Cosmere.Foundation.Extension"/>
        <Using Include="Cosmere.Resources.Extension"/>
        <Using Include="Cosmere.Core.Extension"/>
        <Using Include="Cosmere.Roshar.Extension"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Lib.Harmony" Version="2.3.6"/>
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all">
            <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <ProjectReference Include="..\..\CosmereFoundation\CosmereFoundation\Cosmere.Foundation.csproj"/>
        <ProjectReference Include="..\..\CosmereResources\CosmereResources\Cosmere.Resources.csproj"/>
        <ProjectReference Include="..\..\CosmereCore\CosmereCore\Cosmere.Core.csproj"/>

        <!-- Include all DLLs from potential RimWorld installation paths -->
        <!-- If none of these mastch your path, just copy one of them and change it to your path -->
        <Reference Include="..\..\RimWorldWin64_Data\Managed\*.dll" Condition="Exists('..\..\RimWorldWin64_Data\Managed')">
            <Private>False</Private>
        </Reference>
        <Reference Include="D:\SteamLibrary\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\*.dll" Condition="Exists('D:\SteamLibrary\steamapps\common\RimWorld\RimWorldWin64_Data\Managed')">
            <Private>False</Private>
        </Reference>
        <Reference Include="D:\RimWorld\RimWorldWin64_Data\Managed\*.dll" Condition="Exists('D:\RimWorld\RimWorldWin64_Data\Managed')">
            <Private>False</Private>
        </Reference>
    </ItemGroup>
    <!-- The below condition will check if you've defined a reference called "Assembly-CSharp" and if that reference exists on disk.
        If that reference does not exist, it will add Krafs Rimworld Ref to the project. If it does exist, Krafs won't be added
        as a reference. This basically means that Krafs is treated as a fallback if Assembly-CSharp is not found -->
    <ItemGroup Condition="'@(Reference->WithMetadataValue('Identity', 'Assembly-CSharp')->Metadata('HintPath')->Exists())' == ''">
        <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*"/>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Map\"/>
    </ItemGroup>
</Project>
