using System.Collections.Generic;
using RimWorld;
using Verse;

namespace Cosmere.System.Scadrial.Kandra;

/// <summary>
///     Builds a kandra shape for every animal in the game, at load.
/// </summary>
/// <remarks>
///     A shape cannot just be the animal. RimWorld only hands a draft controller to humanlike
///     pawns and colony mechs, and the Animal render tree cannot draw a humanlike pawn because
///     every node in it reads CurKindLifeStage, which refuses them. So each shape is its own race:
///     the animal's body and picture, humanlike intelligence, and a render tree that takes the
///     graphic from a def extension.
///     <para>
///         Hand-writing those meant a kandra could only ever be the handful of animals somebody
///         had bothered to define. Generating them means it can be anything it can eat, including
///         animals from other mods, and the list keeps itself up to date.
///     </para>
/// </remarks>
[StaticConstructorOnStartup]
public static class KandraShapeGenerator {
    static KandraShapeGenerator() {
        Build();
    }

    public const string RacePrefix = "Cosmere_Scadrial_Race_KandraShape_";
    public const string KindPrefix = "Cosmere_Scadrial_PawnKind_KandraShape_";

    /// <summary>The animal each generated shape copies, so eating one can find it later.</summary>
    private static readonly Dictionary<PawnKindDef, PawnKindDef> shapes = [];

    private static readonly global::System.Reflection.MethodInfo? giveShortHash =
        typeof(ShortHashGiver).GetMethod(
            "GiveShortHash",
            global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static
        );

    private static readonly global::System.Reflection.FieldInfo? takenHashesPerDefType =
        typeof(ShortHashGiver).GetField(
            "takenHashesPerDeftype",
            global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Static
        );

    public static IReadOnlyDictionary<PawnKindDef, PawnKindDef> Shapes => shapes;

    /// <summary>
    ///     Runs on startup rather than during def generation.
    /// </summary>
    /// <remarks>
    ///     Concord's patcher applies long after GenerateImpliedDefs_PreResolve has finished, so
    ///     hooking it there did nothing at all. These defs are never referenced from XML, only
    ///     looked up by name at runtime, so adding them straight to the database afterwards is
    ///     enough.
    /// </remarks>
    private static void Build() {
        List<PawnKindDef> animals = [];
        List<PawnKindDef> all = DefDatabase<PawnKindDef>.AllDefsListForReading;

        for (int i = 0; i < all.Count; i++) {
            if (!Eligible(all[i])) continue;

            animals.Add(all[i]);
        }

        for (int i = 0; i < animals.Count; i++) {
            Generate(animals[i]);
        }

        Cosmere.Core.Logger.Important($"KandraShapeGenerator: built {shapes.Count} animal shapes.");
    }

    /// <summary>
    ///     Anything with a body, a picture and no rider already attached.
    /// </summary>
    /// <remarks>
    ///     Dryads and mechanoids are skipped: a kandra copies bones, and neither has the kind it
    ///     would need. Anything already generated by this is skipped so a hot reload does not
    ///     build shapes of shapes.
    /// </remarks>
    private static bool Eligible(PawnKindDef kind) {
        if (kind.race?.race == null) return false;
        if (!kind.race.race.Animal) return false;
        if (kind.race.race.IsMechanoid) return false;
        if (kind.defName.StartsWith(KindPrefix, global::System.StringComparison.Ordinal)) return false;
        if (kind.lifeStages == null || kind.lifeStages.Count == 0) return false;

        return kind.lifeStages[^1].bodyGraphicData != null;
    }

    private static void Generate(PawnKindDef animal) {
        ThingDef source = animal.race;
        GraphicData picture = animal.lifeStages[^1].bodyGraphicData;

        LifeStageDef stage = ShapeLifeStage(animal, picture);
        ThingDef race = ShapeRace(animal, source, picture, stage);
        PawnKindDef kind = ShapeKind(animal, race);

        shapes[animal] = kind;
    }

    /// <summary>
    ///     Its own life stage, purely to carry silhouette data.
    /// </summary>
    /// <remarks>
    ///     PawnRenderer.RenderPawnAt reads CurLifeStage.silhouetteGraphicData unguarded for every
    ///     humanlike pawn, and the animal life stages have none, so without this it throws once a
    ///     frame. The animal's own picture stands in for the outline.
    /// </remarks>
    private static LifeStageDef ShapeLifeStage(PawnKindDef animal, GraphicData picture) {
        LifeStageDef stage = new LifeStageDef {
            defName = "Cosmere_Scadrial_LifeStage_KandraShape_" + animal.defName,
            label = "adult",
            visible = false,
            reproductive = false,
            silhouetteGraphicData = new GraphicData {
                texPath = picture.texPath,
                graphicClass = typeof(Graphic_Multi),
                drawSize = picture.drawSize,
            },
        };

        Register(stage);
        return stage;
    }

    private static ThingDef ShapeRace(
        PawnKindDef animal,
        ThingDef source,
        GraphicData picture,
        LifeStageDef stage
    ) {
        ThingDef race = new ThingDef {
            defName = RacePrefix + animal.defName,
            label = "kandra " + source.label,
            description = "A kandra wearing the bones of " + source.label
                          + ". It moves like the animal it is copying and thinks like the person underneath.",
            thingClass = typeof(Pawn),
            category = ThingCategory.Pawn,
            selectable = true,
            tickerType = TickerType.Normal,
            altitudeLayer = AltitudeLayer.Pawn,
            useHitPoints = false,
            hasTooltip = true,
            soundImpactDefault = source.soundImpactDefault,
            statBases = source.statBases,
            tools = source.tools,
            uiIconScale = source.uiIconScale,

            // The animal's own comps come along, which is how the shape ends up with the
            // InvestitureHolder that every pawn gets patched onto BasePawn. Without it the
            // Investiture need has nowhere to write and throws the moment a shape goes on.
            comps = [.. source.comps ?? [], new CompProperties_KandraShapePair()],
            modExtensions = [
                new KandraShapeGraphic {
                    texPath = picture.texPath,
                    drawSize = picture.drawSize.x,
                },
            ],
            race = new RaceProperties {
                body = source.race.body,
                baseBodySize = source.race.baseBodySize,
                baseHealthScale = source.race.baseHealthScale,
                baseHungerRate = source.race.baseHungerRate,
                foodType = source.race.foodType,
                leatherDef = source.race.leatherDef,
                lifeExpectancy = source.race.lifeExpectancy,
                hasGenders = source.race.hasGenders,
                nameCategory = source.race.nameCategory == PawnNameCategory.NoName
                    ? PawnNameCategory.HumanStandard
                    : source.race.nameCategory,
                needsRest = true,
                trainability = TrainabilityDefOf.None,

                // The two that make the whole thing work, and the two that are not negotiable.
                intelligence = Intelligence.Humanlike,
                renderTree = DefDatabase<PawnRenderTreeDef>.GetNamed("Cosmere_Scadrial_RenderTree_KandraShape"),

                thinkTreeMain = DefDatabase<ThinkTreeDef>.GetNamed("Humanlike"),
                thinkTreeConstant = DefDatabase<ThinkTreeDef>.GetNamed("HumanlikeConstant"),
                lifeStageAges = [new LifeStageAge { def = stage, minAge = 0f }],
            },
        };

        Register(race);
        return race;
    }

    private static PawnKindDef ShapeKind(PawnKindDef animal, ThingDef race) {
        PawnKindDef kind = new PawnKindDef {
            defName = KindPrefix + animal.defName,
            label = race.label,
            race = race,
            combatPower = animal.combatPower,
            nameMaker = animal.nameMaker,
            nameMakerFemale = animal.nameMakerFemale,
            initialResistanceRange = new FloatRange(10f, 20f),
            initialWillRange = new FloatRange(2f, 4f),
            lifeStages = [new PawnKindLifeStage()],
        };

        Register(kind);
        return kind;
    }

    /// <summary>
    ///     Puts a freshly built def into the database the way the loader would have.
    /// </summary>
    /// <remarks>
    ///     PostLoad resolves the def's own nested data, and the def needs a short hash before
    ///     anything can save a pawn wearing it.
    /// </remarks>
    private static void Register<T>(T def)
        where T : Verse.Def {
        def.PostLoad();
        DefDatabase<T>.Add(def);
        Hash(def, typeof(T));
        def.ResolveReferences();
    }

    /// <summary>
    ///     Hands one def a short hash, reusing vanilla's collision handling.
    /// </summary>
    /// <remarks>
    ///     <c>GiveAllShortHashes</c> is the public way in and the wrong one: it walks every def in
    ///     the game and calls <c>Log.Error</c> on each one that already has a hash, which is all of
    ///     them by this point. That is thousands of red errors and a message-limit cutoff that
    ///     swallows everything logged after it. The private per-def call has none of that.
    /// </remarks>
    private static void Hash(Verse.Def def, global::System.Type defType) {
        if (giveShortHash == null || takenHashesPerDefType == null) return;

        if (takenHashesPerDefType.GetValue(null) is not Dictionary<global::System.Type, HashSet<ushort>> taken) return;

        if (!taken.TryGetValue(defType, out HashSet<ushort>? forType)) {
            forType = [];
            taken[defType] = forType;
        }

        giveShortHash.Invoke(null, [def, defType, forType]);
    }
}
