name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Run tests
        run: dotnet test Cosmere.Tests/Cosmere.Tests.csproj --no-build

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: .scripts/package-lock.json

      - name: Install dependencies
        working-directory: .scripts
        run: npm ci

      - name: Lint TypeScript
        working-directory: .scripts
        run: npm run lint

      - name: Type check
        working-directory: .scripts
        run: npm run typecheck
